name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: bash depends/install_ubuntu_depends.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip, setuptools and wheel
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install synthtiger
      run: pip install .
    - name: Install black
      run: pip install --upgrade black==22.3.0
    - name: Run black
      run: black --check .

  isort:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: bash depends/install_ubuntu_depends.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip, setuptools and wheel
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install synthtiger
      run: pip install .
    - name: Install isort
      run: pip install --upgrade isort==5.10.1
    - name: Run isort
      run: isort --profile black --check .

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: bash depends/install_ubuntu_depends.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip, setuptools and wheel
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install synthtiger
      run: pip install .
    - name: Install mypy
      run: pip install --upgrade mypy
    - name: Run mypy
      run: mypy --ignore-missing-imports --install-types --non-interactive synthtiger

  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: bash depends/install_ubuntu_depends.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip, setuptools and wheel
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install synthtiger
      run: pip install .
    - name: Install pylint
      run: pip install --upgrade pylint
    - name: Run pylint
      run: pylint --errors-only -s y synthtiger

  pytest-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: bash depends/install_ubuntu_depends.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip, setuptools and wheel
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install synthtiger
      run: pip install .
    - name: Install pytest
      run: pip install --upgrade pytest
    - name: Run pytest
      run: pytest .

  pytest-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: bash depends/install_macos_depends.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip, setuptools and wheel
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install synthtiger
      run: pip install .
    - name: Install pytest
      run: pip install --upgrade pytest
    - name: Run pytest
      run: pytest .

  pytest-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
    - name: Add MSYS2 MinGW path
      run: echo "D:\a\_temp\msys64\mingw64\bin" >> $env:GITHUB_PATH
    - name: Install dependencies
      run: msys2 depends/install_windows_depends.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip, setuptools and wheel
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install synthtiger
      run: pip install .
    - name: Install pytest
      run: pip install --upgrade pytest
    - name: Run pytest
      run: pytest .
